/*
 * Created by @tranphuquy19 on 14/08/2020
 * @author: tranphuquy19@gmail.com
 */

// types defined on API
const ALBUM_TYPE = 'album';
const ARTIST_TYPE = 'artist';
const PLAYLIST_TYPE = 'playlist';
const TRACK_TYPE = 'track';

const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_REGISTER = 'USER_REGISTER';

const FIND_TRACKS = 'FIND_TRACKS';
const GET_TRACK = 'GET_TRACK';

const LOAD_ALBUMS = 'LOAD_ALBUMS';

const LOAD_ARTISTS = 'LOAD_ARTISTS';

const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
const CHANGE_VOLUME = 'CHANGE_VOLUME';
const NEXT_TRACK = 'NEXT_TRACK';
const PREVIOUS_TRACK = 'PREVIOUS_TRACK';
const REMOVE_TRACK = 'REMOVE_TRACK';
const SET_TRACKS = 'SET_TRACKS';
const SHUFFLE_TRACKS = 'SHUFFLE_TRACKS';
const TOGGLE_PLAYING = 'TOGGLE_PLAYING';

export {
    ALBUM_TYPE,
    ARTIST_TYPE,
    PLAYLIST_TYPE,
    TRACK_TYPE,

    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTER,

    GET_TRACK,
    FIND_TRACKS,

    LOAD_ALBUMS,

    LOAD_ARTISTS,

    CHANGE_CURRENT_TIME,
    CHANGE_VOLUME,
    NEXT_TRACK,
    PREVIOUS_TRACK,
    REMOVE_TRACK,
    SET_TRACKS,
    SHUFFLE_TRACKS,
    TOGGLE_PLAYING,
}
